//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BsLabPrint.PrinterSetting {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class PrtSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static PrtSetting defaultInstance = ((PrtSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PrtSetting())));
        
        public static PrtSetting Default {
            get {
                return defaultInstance;
            }
        }
    }
}
